osx_image: xcode7.3

dist: trusty
sudo: false

language: c

env:
  - ELECTRON_CACHE=$HOME/.electron

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.1.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.1.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git
  - source ~/.nvm/nvm.sh
  - nvm install 7
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - node --version

install:
- yarn install

script:
- yarn run build

branches:
  - master
